import { Module } from '@nestjs/common';
import { LoggerModule } from 'nestjs-pino';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { DatabaseModule } from './infrastructure/database/database.module';
import { EnvModule } from './infrastructure/env/env.module';
import { QueueModule } from './infrastructure/queues/queue.module';
import { ClinicalAiModule } from './modules/clinical-ai/clinical-ai.module';

@Module({
  imports: [
    // Structured logging (audit finding — "the single highest-leverage
    // addition" per the readiness doc), replacing raw console.log/error
    // everywhere in apps/api. Every HTTP request gets its own bound
    // `req.id` (auto-generated by pino-http) that appears on every log
    // line for that request — the same "one job, one set of traceable
    // log lines" idea as workers/clinical-ai-worker/src/logger.ts's
    // per-job child logger, applied to the request/response side
    // instead. `redact` is defense-in-depth against ever accidentally
    // logging raw provider responses or audio bytes, matching D7's fix.
    LoggerModule.forRoot({
      pinoHttp: {
        level: process.env.LOG_LEVEL ?? 'info',
        redact: {
          paths: ['req.headers.authorization', 'rawResponse', 'audio'],
          censor: '[REDACTED]',
        },
        transport:
          process.env.NODE_ENV === 'production'
            ? undefined
            : {
                target: 'pino-pretty',
                options: { colorize: true, translateTime: 'SYS:HH:MM:ss' },
              },
      },
    }),
    EnvModule,
    DatabaseModule,
    QueueModule,
    ClinicalAiModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
